apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghreview
  namespace: jmainguy-ghreview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghreview
  template:
    metadata:
      labels:
        app: ghreview
    spec:
      containers:
        - name: ghreview
          image: 'hub.soh.re/ghreview:v0.0.2'
          env:
          - name: NODELABEL
            value: node-role.kubernetes.io/compute=true
          - name: ghReviewToken
            value: ADDTOKENHERE
          - name: slackUserID
            value: USERIDHERE
          - name: slackToken
            value: ADDTOKENHERE
          - name: githubName
            value: ADDNAMEHERE
          - name: subscribedRepos
            value: "Example/aebot
Example/aobot
Example/arbot"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 200Mi
